services:
  es01:
    image: poc/elasticsearch:8.15.2
    build:
      context: ./src
      dockerfile: infra/elasticsearch/Dockerfile
    restart: always
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - ES_JAVA_OPTS=-Xms${JVM_HEAP_SIZE} -Xmx${JVM_HEAP_SIZE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    ports:
      - ${ES_PORT}:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es02:
    depends_on:
      - es01
    image: poc/elasticsearch:8.15.2
    build:
      context: ./src
      dockerfile: infra/elasticsearch/Dockerfile
    restart: always
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - ES_JAVA_OPTS=-Xms${JVM_HEAP_SIZE} -Xmx${JVM_HEAP_SIZE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es03:
    depends_on:
      - es02
    image: poc/elasticsearch:8.15.2
    build:
      context: ./src
      dockerfile: infra/elasticsearch/Dockerfile
    restart: always
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - ES_JAVA_OPTS=-Xms${JVM_HEAP_SIZE} -Xmx${JVM_HEAP_SIZE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    image: poc/kibana:8.15.2
    build:
      context: ./src
      dockerfile: infra/kibana/Dockerfile
    restart: always
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - default
    ports:
      - ${KIBANA_PORT}:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata01:
  esdata02:
  esdata03:
  kibana-data:

networks:
  default:
    name: es_poc
